name:                pgn-parser
version:             0.1.0.0
github:              "lsund/pgn-parser"
license:             BSD3
author:              "Ludvig Sundström"
maintainer:          "lud.sund@gmail..com"
copyright:           "2018 Ludvig Sundström"

extra-source-files:
- README.md
- ChangeLog.md

description: "Program for parsing PGN into SQL-friendly data structures."

dependencies:
- base >= 4.7 && < 5
- protolude
- parsec
- text

library:
  source-dirs: src

tests:
  pgn-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pgn-parser
