name:                PGNParser
version:             0.1.0.0
github:              "lsund/PGNParser"
license:             BSD3
author:              "Ludvig Sundström"
maintainer:          "lud.sund@gmail..com"
copyright:           "2018 Ludvig Sundström"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/githubuser/PGNParser#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- parsec
- text

library:
  source-dirs: src

tests:
  PGNParser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PGNParser
